### ISSUE TITLE
Support for multiple sprites (bug?) 

### ISSUE THREAD

**Issue by mnovbaalen** [soimy/atlasify#8]
Atlasify is a great way to generate spritesheets!

However, when there are more images than fit on the spritesheet, Atlasify generates multiple spritesheet files with the same name. This results in having a spritesheet file with only the remainder of images that did not fit on the previous spritesheet(s).

Some info that might help:
The problem seems to be in `atlasify.ts` / `atlasify.js`, in the pack function. The binName is not unique when no tags are used. When 
```
            let binName = basename;
```
is replaced with
```
            let binName = basename + '_' + index;
```
then multiple spritesheet files are generated.

This is not a good solution, but just a quick 'see if this helps' hack for my specific use case.

Please fix this in a proper way.

**Comment by soimy** [comment]
Thanks for the report, I'll look into it.

**Comment by soimy** [comment]
Fixed via c554cdb
Should work as you expected now.

**Comment by mnovbaalen** [comment]
Thank you very much @soimy, I'll give it a try!

**Comment by mnovbaalen** [comment]
I'm very sorry for this late replay, but I can confirm that the fix works for me!

**Comment by mnovbaalen** [comment]
@soimy I made this change to atlasify.ts to get things working:

```
--- src/atlasify.ts	(date 1578929561671)
+++ src/atlasify.ts	(date 1578929561671)
@@ -329,11 +329,12 @@
             // Add tag to the last sheet to control mustache trailing comma
             serializedSheet[serializedSheet.length - 1].last = true;
 
+            const spritesheetId = tagCount[tag];
             // prepare spritesheet data
             this._spritesheets[index] = {
-                id: tagCount[tag],
+                id: spritesheetId,
                 name: binName,
-                imageName: `${binName} .${ext}`,
+                imageName: `${binName}.${spritesheetId}.${ext}`,
                 imageFormat: "RGBA8888",
                 width: bin.width,
                 height: bin.height,
```

**Comment by soimy** [comment]
Thanks for the report

**Comment by mnovbaalen** [comment]
Thank you @soimy for fixing this. It is working correctly now.
